routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DiagnosisController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InformasiController;
use App\Http\Controllers\KonsultasiController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MasterIdentiController;
use App\Http\Controllers\MasterJenisController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\RuleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('proses_login', [AuthController::class, 'proses_login'])->name('proses_login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

//Register
Route::get('register', [RegisterController::class, 'register'])->name('register');
Route::post('register/action', [RegisterController::class, 'actionregister'])->name('actionregister');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');

    //Role Pakar
    Route::group(['middleware' => ['cek_login:pakar']], function () {
        //Master Jenis Serangan
        Route::get('master_jenis', [MasterJenisController::class, 'index'])->name('master_jenis.index')->withoutMiddleware('cek_login:admin');
        Route::post('master_jenis', [MasterJenisController::class, 'store'])->name('master_jenis.store');
        Route::get('master_jenis/form', [MasterJenisController::class, 'create'])->name('master_jenis.create');
        Route::get('master_jenis/{id}', [MasterJenisController::class, 'edit'])->name('master_jenis.edit');
        Route::put('master_jenis/{id}', [MasterJenisController::class, 'update'])->name('master_jenis.update');
        Route::delete('master_jenis/{id}', [MasterJenisController::class, 'delete'])->name('master_jenis.delete');

        //Master Identifikasi
        Route::get('master_identi', [MasterIdentiController::class, 'index'])->name('master_identi.index');
        Route::post('master_identi', [MasterIdentiController::class, 'store'])->name('master_identi.store');
        Route::get('master_identi/form', [MasterIdentiController::class, 'create'])->name('master_identi.create');
        Route::get('master_identi/{id}', [MasterIdentiController::class, 'edit'])->name('master_identi.edit');
        Route::put('master_identi/{id}', [MasterIdentiController::class, 'update'])->name('master_identi.update');
        Route::delete('master_identi/{id}', [MasterIdentiController::class, 'delete'])->name('master_identi.delete');

        //Transaksi Rule
        Route::get('t_rule', [RuleController::class, 'index'])->name('t_rule.index');
        Route::post('t_rule', [RuleController::class, 'store'])->name('t_rule.store');
        Route::get('t_rule/form', [RuleController::class, 'create'])->name('t_rule.create');
        Route::get('t_rule/{id}', [RuleController::class, 'edit'])->name('t_rule.edit');
        Route::put('t_rule/{id}', [RuleController::class, 'update'])->name('t_rule.update');
        Route::delete('t_rule/{id}', [RuleController::class, 'delete'])->name('t_rule.delete');

        //Transaksi Diagnosis
        Route::get('hasil-diagnosis', [DiagnosisController::class, 'hasilDiagnosis'])->name('diagnosis.hasil');
    });

    //Role admin
    Route::group(['middleware' => ['cek_login:admin']], function () {
        Route::resource('users', UserController::class);
    });
    //Role Guest
    Route::get('diagnosis', [DiagnosisController::class, 'index'])->name('diagnosis.index');
    Route::get('outputDiagnosis', [DiagnosisController::class, 'output'])->name('diagnosis.output');
    Route::post('prosesDiagnosis', [DiagnosisController::class, 'prosesDiagnosis'])->name('diagnosis.prosesDiagnosis');
    Route::get('informasi', [InformasiController::class, 'index'])->name('informasi.index');

    Route::get('konsultasi', [KonsultasiController::class, 'index'])->name('konsultasi');
    Route::get('konsultasi/tambah', [KonsultasiController::class, 'create'])->name('konsultasi.create');
    Route::post('konsultasi/tambah', [KonsultasiController::class, 'store'])->name('konsultasi.store');
    Route::get('konsultasi/detail/{id}', [KonsultasiController::class, 'detail'])->name('konsultasi.detail');
    Route::put('konsultasi/update/{id}', [KonsultasiController::class, 'update'])->name('konsultasi.update');
    Route::delete('konsultasi/delete/{id}', [KonsultasiController::class, 'delete'])->name('konsultasi.delete');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $table = 'users';
    protected $primaryKey = 'id';

    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Auth\Events\Validated;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use function GuzzleHttp\Promise\all;

class UserController extends Controller
{
    public function index()
    {
        $user = User::latest()->paginate(20);

        return view('users.index', compact('user'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('users.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|unique:users',
            'password' => 'required',
            'role' => 'required',
        ]);

        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->role = request()->role;
        $user->save();
        return redirect('users')->with('success', 'Tambah Data User Berhasil');
    }

    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
        ]);

        $user->update($request->all());

        return redirect()->route('users.index')
            ->with('success', 'Data User Berhasil Di Update');
    }

    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('users.index')
            ->with('success', 'Data User Berhasil Di Hapus');
    }
}

resources/views/users/create.blade.php
@extends('master')

@section('home')
    <div class="card">
        <div class="card-body">
            <main id="main" class="main">
                <h5 class="card-title">Form Tambah User</h5>

                <div class="pull-left">
                    <a class="btn btn-success mb-3" href="{{ route('users.index') }}"> Kembali</a>
                </div>
                <br>
                <!-- General Form Elements -->
                <form action="{{ url('users') }}" method="POST">
                    @csrf
                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Nama</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="name">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" name="email">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" name="password">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Role</label>
                        <div class="col-sm-10">
                            <select class="form-select" name="role" aria-label="Default select example">
                                <option selected disabled hidden>Pilih Role</option>
                                <option value="admin">Admin</option>
                                <option value="pakar">Pakar</option>
                            </select>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-xs-6 col-sm-6 col-md-4 text-end">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>

                </form><!-- End General Form Elements -->
            </main>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('master')

@section('home')
    <div class="card">
        <div class="card-body">
            <main id="main" class="main">
                <h5 class="card-title">Form Edit User</h5>

                <div class="pull-left">
                    <a class="btn btn-success mb-3" href="{{ route('users.index') }}"> Kembali</a>
                </div>
                <br>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        Anda salah meng-input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <!-- General Form Elements -->
                <form action="{{ url('users', $user->id) }}" method="POST">
                    @csrf
                    @method('PUT')

                    <div class="row mb-3">
                        <label for="inputText" class="col-sm-2 col-form-label">Nama</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="name" value="{{ $user->name }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" name="email" value="{{ $user->email }}">
                        </div>
                    </div>
                    {{-- <div class="row mb-3">
                        <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" name="password" value="{{ $user->password }}">
                        </div>
                    </div> --}}

                    <div class="row mb-3">
                        <div class="col-xs-6 col-sm-6 col-md-4 text-end">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>

                </form><!-- End General Form Elements -->
            </main>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('master')

@section('home')
    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Data User</h1>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Daftar User</h5>

                            <div class="pull-left">
                                <a class="btn btn-success mb-3" href="{{ route('users.create') }}"> Tambah +</a>
                            </div>

                            <!-- Table with stripped rows -->
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">No</th>
                                        <th scope="col">Nama</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Role</th>
                                        <th scope="col">Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($user as $users)
                                        <tr>
                                            <th scope="row">{{ ++$i }}</th>
                                            <td>{{ $users->name }}</td>
                                            <td>{{ $users->email }}</td>
                                            <td>{{ $users->role }}</td>
                                            <td>
                                                <form action="{{ route('users.destroy', $users->id) }}" method="POST">


                                                    <a class="btn btn-primary"
                                                        href="{{ route('users.edit', $users->id) }}">Edit</a>

                                                    @csrf
                                                    @method('DELETE')

                                                    <button type="submit" class="btn btn-danger">Hapus</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <!-- End Table with stripped rows -->

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->
@endsection